Compile with warnings as errors (#234)
Closes #193.

Final part of making our build stricter — treating compile warnings as errors.

The change also includes docker arguments to propagate interactive output, thus get colors of warnings/errors locally and on CI (as well as CTRL+C support and other signals propagated through interactive mode).

Tested by adding unused variable:

```console
Building debug version of Mainframer...
   Compiling mainframer v3.0.0-dev (/opt/project)
error: unused variable: `x`
  --> src/main.rs:30:9
   |
30 |     let x = 1;
   |         ^ help: consider using `_x` instead
   |
   = note: `-D unused-variables` implied by `-D warnings`

error: aborting due to previous error

error: Could not compile `mainframer`.

To learn more, run the command again with --verbose.

Test run FAILED, 1 test(s).
To log each step: export DEBUG_MODE_FOR_ALL_TESTS=true
```